### ISSUE TITLE
will there be patch for 2023.1.0?

### ISSUE THREAD

**Issue by zhuoqun-chen** [j3soon/isaac-extended#1]
Hi,

Thank you for making this repo, I can easily create a conda env with isaac sim because the patch you provided in 2022 version. May I ask is their anything new to pay attention to for today's new `2023.1.0` release?

**Comment by j3soon** [comment]
I'm delighted to hear that someone is using the patches provided in this repo. :)

I have just uploaded the corresponding patch for Isaac Sim 2023.1.0.

Thanks for opening this issue.
